export const brandLogos = [
  { name: 'AEG', src: '/brands/aeg.png' },
  { name: 'ASKO', src: '/brands/asko.png' },
  { name: 'BORA', src: '/brands/bora.png' },
  { name: 'CIARKO DESIGN', src: '/brands/ciarko-design.png' },
  { name: 'COSENTINO', src: '/brands/cosentino.png' },
  { name: 'ELECTROLUX', src: '/brands/electrolux.png' },
  { name: 'ELICA', src: '/brands/elica.png' },
  { name: 'FALMEC', src: '/brands/falmec.png' },
  { name: 'FLORIM', src: '/brands/florim.png' },
  { name: 'FRANKE', src: '/brands/franke.png' },
  { name: 'KERNAU', src: '/brands/kernau.png' },
  { name: 'LIEBHERR', src: '/brands/liebherr.png' },
  { name: 'MIELE', src: '/brands/miele.png' },
  { name: 'NORDBERG', src: '/brands/nordberg.png' },
  { name: 'QUOOKER', src: '/brands/quooker.png' },
  { name: 'REGINOX', src: '/brands/reginox.png' },
  { name: 'SCHOCK', src: '/brands/schock.png' },
  { name: 'SIEMENS', src: '/brands/siemens.png' },
  { name: 'SMEG', src: '/brands/smeg.png' },
]
